# Generated by Django 2.1.3 on 2018-11-29 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConductivityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppm_truncheon', models.CharField(default=6.2, max_length=50)),
                ('ppm_eutech', models.CharField(default=0.2, max_length=50)),
                ('ppm_hanna', models.CharField(default=4.3, max_length=50)),
                ('ec', models.CharField(default=2.3, max_length=50)),
                ('cf', models.CharField(default=0.1, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_size', models.IntegerField()),
                ('water_hardness', models.IntegerField()),
                ('conductivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.ConductivityModel')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_feeding', models.CharField(max_length=50)),
                ('normal_feeding', models.CharField(max_length=50)),
                ('heavy_feeding', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SoilModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terra', models.CharField(max_length=50)),
                ('aqua', models.CharField(max_length=50)),
                ('coco', models.CharField(max_length=50)),
                ('cogr', models.CharField(max_length=50)),
                ('hydro_soft', models.CharField(max_length=50)),
                ('hydro_hard', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WaterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=50)),
                ('hard', models.CharField(max_length=50)),
                ('custom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='fertilizermodel',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.ScheduleModel'),
        ),
        migrations.AddField(
            model_name='fertilizermodel',
            name='soil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.SoilModel'),
        ),
        migrations.AddField(
            model_name='fertilizermodel',
            name='water',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.WaterModel'),
        ),
    ]
