# Generated by Django 2.1.3 on 2018-12-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilmodel',
            old_name='aqua',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='soilmodel',
            name='coco',
        ),
        migrations.RemoveField(
            model_name='soilmodel',
            name='cogr',
        ),
        migrations.RemoveField(
            model_name='soilmodel',
            name='hydro_hard',
        ),
        migrations.RemoveField(
            model_name='soilmodel',
            name='hydro_soft',
        ),
        migrations.RemoveField(
            model_name='soilmodel',
            name='terra',
        ),
    ]
