# Generated by Django 2.1.3 on 2018-12-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_auto_20181201_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductivitymodel',
            name='cf',
        ),
        migrations.RemoveField(
            model_name='conductivitymodel',
            name='ec',
        ),
        migrations.RemoveField(
            model_name='conductivitymodel',
            name='ppm_eutech',
        ),
        migrations.RemoveField(
            model_name='conductivitymodel',
            name='ppm_hanna',
        ),
        migrations.RemoveField(
            model_name='conductivitymodel',
            name='ppm_truncheon',
        ),
        migrations.RemoveField(
            model_name='watermodel',
            name='custom',
        ),
        migrations.RemoveField(
            model_name='watermodel',
            name='hard',
        ),
        migrations.RemoveField(
            model_name='watermodel',
            name='soft',
        ),
        migrations.RemoveField(
            model_name='watermodel',
            name='standard',
        ),
        migrations.AddField(
            model_name='conductivitymodel',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='watermodel',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='soilmodel',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
