# Generated by Django 2.1.3 on 2018-12-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_auto_20181201_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemodel',
            name='heavy_feeding',
        ),
        migrations.RemoveField(
            model_name='schedulemodel',
            name='light_feeding',
        ),
        migrations.RemoveField(
            model_name='schedulemodel',
            name='normal_feeding',
        ),
        migrations.AddField(
            model_name='schedulemodel',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
