# Generated by Django 2.1.3 on 2018-12-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_auto_20181201_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizermodel',
            name='conductivity',
        ),
        migrations.RemoveField(
            model_name='fertilizermodel',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='fertilizermodel',
            name='soil',
        ),
        migrations.RemoveField(
            model_name='fertilizermodel',
            name='water',
        ),
        migrations.DeleteModel(
            name='ConductivityModel',
        ),
        migrations.DeleteModel(
            name='FertilizerModel',
        ),
        migrations.DeleteModel(
            name='ScheduleModel',
        ),
        migrations.DeleteModel(
            name='SoilModel',
        ),
        migrations.DeleteModel(
            name='WaterModel',
        ),
    ]
